version: '3'
services:
  web:
    build: .
    ports:
      - '3033:3033'
    env_file: .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14
    env_file: .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
